### ISSUE TITLE
Inline embedded notes won't expand in Quip

### ISSUE THREAD

**Issue by akhilrazdan** [sblakey/obsidian-quip#28]
Steps to reproduce
1. Make sure "Inline embedded notes" toggle is turned on
2. Add a note with embedded link to another note
 ```
 ![[Another page]]
 ```
3. Do "Quip: Publish as new document" or "Update existing Quip document", the embedded notes are not expanded. 

The note is not embedded, and just Another Page gets outputted to the Quip document.

**Comment by sblakey** [comment]
I have reproduced the problem with two trivial notes:

---

Test Embedded
```
This is the embedded content
```

---

Test Embedding

```
This is a test of inline embedding.

![[Test Embedded]]
```

---

Resulting Quip document w/o head

```
<!doctype html>
<html><body><h1 id='GVJ9CAScxA6'>Test Embedding</h1>

This is a test of inline embedding.<br/>

<br/>

Test Embedded<br/>

</body></html>
```

**Comment by sblakey** [comment]
Found an error in the Quip eleectron console:
```
Quip plugin encountered an error trying to load an embedded note: TypeError: r.addChild is not a function
```

It looks like this is due to a change in the `render` API of later versions of Obsidian.md
