### ISSUE TITLE
Allow Quip New Document command from the Reading View

### ISSUE THREAD

**Issue by isaaclen** [sblakey/obsidian-quip#7]
The Quip publish as new document command is not available if the note is in Reading view.  Not a huge deal to swap to edit view, but I am using another plugin [ https://github.com/bwydoogh/obsidian-force-view-mode-of-note ] to force certain "dashboard/summary" notes to always be in reading view (due to rendering reasons, using custom buttons, etc).  So, exporting these specific pages will always require swapping to Editing view, exporting and then swapping back.  And unfortunately for me, these are the kind of notes I will be looking to export. 

Would be nice if the command was available from the reading view, even if it needs to temporarily and automatically swap to editing, export and then swap back.

**Comment by sblakey** [comment]
This doesn't look like it should be hard to tackle.

**Comment by sblakey** [comment]
Reproduced issue with current tip code.
