### ISSUE TITLE
Update existing Quip Document if the Quip URL is already in the frontmatter of the note

### ISSUE THREAD

**Issue by isaaclen** [sblakey/obsidian-quip#8]
Currently plugin can only create new documents, and populates the last known Quip URL in the frontmatter.  As expected, for a previously exported note "Create new Document" command creates a new document in Quip and replaces the current Quip URL in the frontmatter. 

But, it would be very useful that if the previous Quip url is already in the frontmatter to not create a new document, but to update the existing document in Quip at that url with the current content of the note. [ https://quip.com/dev/automation/documentation/all#operation/editDocument ]

This also enables issue #10

**Comment by sblakey** [comment]
Agreed that this would be useful, but the Quip API makes this shockingly difficult. I basically need to make section-by-section diff-and-update, or find a way to append the new document and wipe out the existing sections...

**Comment by isaaclen** [comment]
For my scenario, I was thinking of just "wiping" the existing document in Quip while preserving the Quip url, not doing a section-by-section diff, which I agree sounds rather involved.  The user story I have in mind is that my vault is really the "source" and Quip is just a handy way to convey some of the information to other people using quip (updates, current status, etc).  If I can hand out a Quip url to other people that I know won't change and I just keep it updated from time to time, that's very useful, rather than always creating new URLs for each export.

**Comment by sblakey** [comment]
Yes, all I'm saying is that the Quip API enforces working section-by-section, and doesn't support a trivial unilateral overwrite.

It's tricky, but not impossible.

**Comment by isaaclen** [comment]
Gotcha.  I just read the docs out of curiosity and yeah, the Quip way of doing sections isn't pretty at all for this use case.
