### ISSUE TITLE
Custom Quip title/header on export of Note to Quip

### ISSUE THREAD

**Issue by isaaclen** [sblakey/obsidian-quip#9]
The title/header of the note in Obsidian makes sense in context, but when exported as a standalone note to Quip, the title doesn't necessarily always make sense, or would benefit from adding additional information because it is probably for a different audience.

Would be nice if when exporting:
- Prompt for a custom title of the note to be placed in quip, so the user can override or add info
- Add the custom title supplied to the frontmatter of the note (quip-export-title, etc) so it can be reused in future exports without prompting

Bonus: enable a datetime placeholder in the custom title, like {{YYYY-MM-DD hh:mm:ss}}, so that whenever the document is exported, the title in Quip will automatically have that timestamp in the header.  And maybe a placeholder of {{title}} so that it could dynamically allow for appending to the current note title, like: "{{title}} - For Review by Joe Smith", etc.

**Comment by sblakey** [comment]
Unfortunately, it looks like the Quip API also doesn't support updating a title after a document is created 🙄

https://github.com/quip/quip-api/issues/89

**Comment by sblakey** [comment]
So, the feature I've built is more limited, but documented in the latest README.md.

If you turn on the "Add Note name as Quip document title" setting, the plugin will set a title for you and use the note filename, minus the ".md" suffix.

If you want to *override* this with a more customized title, you can set the `title` variable in your note's front matter.

I'm not inclined to build templating support into this plugin; I figure that is doable within your Obsidian templating/automation system of choice.
